// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_VentadeVehiculos.Data;

#nullable disable

namespace Proyecto_VentadeVehiculos.Migrations
{
    [DbContext(typeof(Proyecto_VentadeVehiculosContext))]
    partial class Proyecto_VentadeVehiculosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_VentadeVehiculos.Models.Comprador", b =>
                {
                    b.Property<int>("IdComprador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComprador"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("fechanacimiento")
                        .HasColumnType("date");

                    b.HasKey("IdComprador");

                    b.ToTable("Comprador");
                });

            modelBuilder.Entity("Proyecto_VentadeVehiculos.Models.Transaccion", b =>
                {
                    b.Property<int>("IdTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransaccion"));

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdComprador")
                        .HasColumnType("int");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<int>("IdVendedor")
                        .HasColumnType("int");

                    b.Property<double>("PrecioFinal")
                        .HasColumnType("float");

                    b.HasKey("IdTransaccion");

                    b.HasIndex("IdComprador");

                    b.HasIndex("IdVehiculo");

                    b.HasIndex("IdVendedor");

                    b.ToTable("Transaccion");
                });

            modelBuilder.Entity("Proyecto_VentadeVehiculos.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoCombustible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("kilometraje")
                        .HasColumnType("real");

                    b.Property<double>("precio")
                        .HasColumnType("float");

                    b.HasKey("IdVehiculo");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("Proyecto_VentadeVehiculos.Models.Vendedor", b =>
                {
                    b.Property<int>("IdVendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVendedor"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("fechanacimiento")
                        .HasColumnType("date");

                    b.HasKey("IdVendedor");

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("Proyecto_VentadeVehiculos.Models.Transaccion", b =>
                {
                    b.HasOne("Proyecto_VentadeVehiculos.Models.Comprador", "Comprador")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdComprador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_VentadeVehiculos.Models.Vehiculo", "Vehiculo")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_VentadeVehiculos.Models.Vendedor", "Vendedor")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdVendedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Vehiculo");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Proyecto_VentadeVehiculos.Models.Comprador", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("Proyecto_VentadeVehiculos.Models.Vehiculo", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("Proyecto_VentadeVehiculos.Models.Vendedor", b =>
                {
                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
